/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'lilianngweta' at '6/22/16 11:51 AM' with Gradle 2.13
 *
 * @author lilianngweta, @date 6/22/16 11:51 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
